name: appforthat
favicon: null
layout_spectrum: 0.6335650822147727
typography_spectrum: 0.83571
title: A Place for Apps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#fefefe'
    - '#9b9c9e'
    - '#5a5a5a'
    - '#df2729'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
